name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies with pipenv
      run: |
        pip install pipenv==2018.10.13
        pipenv install --deploy --dev
        pipenv install flake8
        pipenv install isort
        pipenv install mypy
        pipenv install pytest

    - run: pipenv run isort --recursive --diff
    - run: pipenv run mypy
    - run: pipenv run pytest --cov --cov-fail-under=100
    - run: pipenv run pipenv lock
